# Generated by Django 4.2.16 on 2026-09-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Administrator'), ('delivery', 'Delivery Personnel'), ('store_owner', 'Store Owner')], default='customer', max_length=20),
        ),
    ]
